name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Start application
        run: npm start & # Chạy server ở background
        env:
          PORT: 3000 # Đảm bảo port là 3000 (nếu cần)

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3000 # Chờ server khởi động

      - name: Run Cypress
        run: npx cypress run --browser chrome

      - name: Upload Cypress artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: |
            cypress/videos/
            cypress/screenshots/