name: Cypress Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v5
        with:
          start: npm start  # Khởi chạy ứng dụng trước khi test (nếu cần)
          wait-on: 'http://localhost:3000'